### ISSUE TITLE
React.js templating

### ISSUE THREAD

**Issue by SatadruBhattacharjee** [puzzle-js/puzzle-js#104]
Any example, docs of using react templating? 
Thanks

**Comment by erdoganoksuz** [comment]
@SatadruBhattacharjee  hi,
Im working on it.

**Comment by SatadruBhattacharjee** [comment]
@erdoganoksuz , Any update on the react templating. I have created a micro front-end using [node-tailor ](https://www.npmjs.com/package/node-tailor) . I feel puzzle-js gives more flexibility and like to do a similar demo using puzzle-js .
Thanks

**Comment by erdoganoksuz** [comment]
> @erdoganoksuz , Any update on the react templating. I have created a micro front-end using [node-tailor ](https://www.npmjs.com/package/node-tailor) . I feel puzzle-js gives more flexibility and like to do a similar demo using puzzle-js .
> Thanks

Sorry im so busy but i hope this weekend create a demo with react.

**Comment by zwicker** [comment]
Any update on this one? Eager to try it with react.

**Comment by zwicker** [comment]
and SSR

**Comment by Rikezenho** [comment]
+1
I can help if needed!
I'm currently researching which framework we will use for micro front-ends with SSR, and PuzzleJS is very interesting.

**Comment by eliecer2323** [comment]
Does anybody has this example or any knowledge about how to do it?
