### ISSUE TITLE
SEO Friendly?

### ISSUE THREAD

**Issue by ghost** [puzzle-js/puzzle-js#211]
Can you explain or add it to docs how it is SEO friendly?

**Comment by erdoganoksuz** [comment]
First of all sorry for the late response we so busy with 11.11 events.
Let's start with live example.
We develop [m.trendyol.com](https://m.trendyol.com/) with puzzle-js and our homepage like this;

![m trendyol com_(iPhone 6_7_8 Plus)](https://user-images.githubusercontent.com/13199681/68798790-20825800-0668-11ea-9a30-1dff97858453.png)

I draw our gateways with different colors 

Red: Search-Gateway
Blue: Account-Gateway
Green: Browsing-Gateway
And we have a Storefront project this project manages all gateways and generates pages.

Every gateway contains specific fragments. For this case, we use 4 fragments to generate our page.

Search gateway contains Search-Bar fragment and Header-Fragment.
Browsing gateway contains Boutique-List fragment.
Account gateway contains Cookie-policy.

Work schema;
<img width="723" alt="Screen Shot 2019-11-13 at 23 12 16" src="https://user-images.githubusercontent.com/13199681/68800399-1150d980-066b-11ea-9989-f151ca980d4d.png">


Every fragment renders only own components like react or vue components, for example;
SEARCH-BAR renders only 1 input.
COOKIE-POLICY renders only 1 div with policy content.

When a user visiting m.trendyol.com, our storefront project finds a matched route and renders that page with the puzzle-js template engine. This case our route page like this;

<img width="473" alt="Screen Shot 2019-11-13 at 23 29 33" src="https://user-images.githubusercontent.com/13199681/68801612-7a395100-066d-11ea-9909-5da4eb869fc8.png">

Puzzle-js detects  `<fragment/>` tag says "**ok this part of HTML should come from **gateway** I should check configuration file and get rendered HTML from **fragment** name. In this time I cannot end request."**
All fragments its done puzzle-js; **"ok I got all the fragments from gateways and generate a page with them"**

Generated page a static SEO friendly HTML file.

**Comment by atilkan** [comment]
As i understand, static html pages loaded from client javascript. I am aware google crawler can run js and see the page. The question is; Does this run without javascript on the client. Because i tried to disable js and fragments have not loaded.

**Comment by Acanguven** [comment]
For adding some addition to @erdoganoksuz, PuzzleJs' one of the most important feature is chunked transfer. Like and single page application with multiple async components coming from different apis, PuzzleJs can stream html chunks from server side and browser can start rendering immediately. Thus, browser always renders progressively, not waiting for the slowest response to finish. This improves page load metrics drastically and also Google can get fully server side rendered html content.

**Comment by erdoganoksuz** [comment]
> Thanks for the detailed explanation. As i understand, static html pages loaded javascript on the client. I am aware google crawler can run js and see the page. The question is; Does this run without javascript on the client. Because i tried to disable js and fragments have not loaded.

No, Visit [m.trendyol.com](https://m.trendyol.com/) and block javascript. You will see the page opened successfully because we create pages on the server-side and send them with HTTP chunked transfer.

**Comment by Acanguven** [comment]
> Thanks for the detailed explanation. As i understand, static html pages loaded javascript on the client. I am aware google crawler can run js and see the page. The question is; Does this run without javascript on the client. Because i tried to disable js and fragments have not loaded.

Nope, client library is a must to support all features. It adds some great features like browser-gateway communication for asynchronous fragments. We didn't documented it yet but you can simply add `client-async` attribute to fragment. Or `async-c2` for decentralized fragment responses.

**Comment by cagataycali** [comment]
As well as, we’ll update documentation for new features 🥳

**Comment by atilkan** [comment]
Documentation would be nice. Thank you all.

**Comment by atilkan** [comment]
FYI. Demo doesn't with disabled js.
http://178.128.201.193:4444/

**Comment by Acanguven** [comment]
@atilkan Please view the source of it.
