### ISSUE TITLE
Why not just for..in ?

### ISSUE THREAD

**Issue by atilkan** [puzzle-js/puzzle-js#231]
**for..in** would be faster and shorter in this case. What do you think?

https://github.com/puzzle-js/puzzle-js/blob/38c04c9b322a614cfa0ab27c1afd3c564396e59b/src/api.ts#L49

**Comment by cagataycali** [comment]
Could you proof is `Object.keys` slower than `for..in`

https://jsperf.com/for-in-vs-object-keys

**Comment by atilkan** [comment]
But there is also **forEach**.

**Comment by atilkan** [comment]
Even if it is faster, this case is more suitable for Object.entries(). But fastness is not always best approach. Sometimes shorter is better.

**Comment by cagataycali** [comment]
For puzzle’s case, faster first approach is more suitable. If you have any performance recommendations about this perspective is great. Please think in our shoes, code readibilty obviously the most important aim for better code but if the code readable, faster is better. If the code is mess or unmaintainable, readibility is our choice in this case.

I think you understand the code when you read at first sight. That’s valid for us.

**Comment by atilkan** [comment]
I think for..in is faster and more readable. And shorter.

**Comment by cagataycali** [comment]
We're looking for your pull request and tests!
Thx.

**Comment by atilkan** [comment]
`Object.keys(object).forEach( item => {  
   item.prop  
})`  

`for(const item in object){  
   item.prop  
}`  

I will definitely test these two.

**Comment by cagataycali** [comment]
OK. Modify code, write benchmark tests and open PR for this!

**Comment by cagataycali** [comment]
Looking 4 your pull requests, closed for now.

**Comment by atilkan** [comment]
@cagataycali 
I answer my own question. For..in loops inherited properties too so we need to use a check with hasOwnProperty and that makes the loop slower. 
But for the usecase here, Object.entries() is the way to go since you are trying to access both key and value.
