### ISSUE TITLE
puzzle-warden with puzzle-js

### ISSUE THREAD

**Issue by SatadruBhattacharjee** [puzzle-js/puzzle-js#99]
`puzzle-warden` seems to be quite interesting, can this seat between the storefront and Gateway route and before the storefront pages, Thanks.

**Comment by Acanguven** [comment]
Yes, it is integrated with PuzzleJs. 

When providing a gateway configuration, you can also provide Warden configuration.
```
...
name: "header",
      testCookie: "header_cookie",
      version: "1.0.0",
      warden: {
        identifier: "{cookie.user}_{!!cookie.t}{query.showsearch}{query.iconenabled}{query.fix}{query.sid}{query.lid}",
        holder: true,
        cache: true
      },
      render: {
        url: "/*",
        selfReplace: true,
        placeholder: true,
        middlewares: []
      },
      versions: {
...
```

If you want to use custom plugins you should register them on your storefront project. You can check the [documentation](https://github.com/puzzle-js/puzzle-warden#custom-plugins) of Warden.

You can access Warden instance from PuzzleJs using.

`PuzzleJs.warden.registerCachePlugin('couchbase', couchbaseCachePlugin);`
